// Server.idl : IDL source for Server.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (Server.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";
	[
		object,
		uuid(45D4EE91-6A6D-11D3-9DDF-006097FAD0B8),
		dual,
		helpstring("IAutomation Interface"),
		pointer_default(unique)
	]
	interface IAutomation : IDispatch
	{
		[id(1), helpstring("method Hello")] HRESULT Hello([in] BSTR message);
	};

[
	uuid(45D4EE85-6A6D-11D3-9DDF-006097FAD0B8),
	version(1.0),
	helpstring("Server 1.0 Type Library")
]
library SERVERLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	[
		uuid(45D4EE92-6A6D-11D3-9DDF-006097FAD0B8),
		helpstring("Automation Class")
	]
	coclass Automation
	{
		[default] interface IAutomation;
	};
};
