// Component.idl : IDL source for Component.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (Component.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

	[
		object,
		uuid(DBC88FD0-4033-11D2-8172-006097FAD0B8),
		dual,
		helpstring("IControl Interface"),
		pointer_default(unique)
	]
	interface IControl : IDispatch
	{
		[id(1), helpstring("method SquareRoot")] HRESULT SquareRoot([in] double number, [out, retval] double* pResult);
		[id(2), helpstring("method Average")] HRESULT Average([in] double number1, [in] double number2, [out, retval] double* pResult);
		[id(3), helpstring("method Multiply")] HRESULT Multiply([in] double number1, [in] double number2, [out, retval] double* pResult);
		[id(4), helpstring("method Square")] HRESULT Square([in] double number, [out, retval] double* pResult);
	};
[
	uuid(DBC88FC3-4033-11D2-8172-006097FAD0B8),
	version(1.0),
	helpstring("Component 1.0 Type Library")
]
library COMPONENTLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	[
		uuid(DBC88FD2-4033-11D2-8172-006097FAD0B8),
		helpstring("Control Class")
	]
	coclass Control
	{
		[default] interface IControl;
	};
};
