// QABankTransfer.idl : IDL source for QABankTransfer.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (QABankTransfer.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";
	[
		object,
		uuid(C565DA99-DF4B-45AE-9157-35C7F4A99CF4),
		dual,
		helpstring("ITransfer Interface"),
		pointer_default(unique)
	]
	interface ITransfer : IDispatch
	{
		[id(1), helpstring("method Transfer")] HRESULT Transfer([in] double amount, [in] BSTR fromAccount, [in] BSTR toAccount);
	};

[
	uuid(8778F9B4-AEF1-40EF-A9D9-F81256D20D3D),
	version(1.0),
	helpstring("QABankTransfer 1.0 Type Library")
]
library QABANKTRANSFERLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	[
		uuid(ADC27ED6-D653-4913-A338-8B07E02F6AD3),
		helpstring("Transfer Class")
	]
	coclass Transfer
	{
		[default] interface ITransfer;
	};
};
