#include <olectl.h>
// Fire.idl : IDL source for Fire.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (Fire.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

	

[
	object,
	uuid(23D68043-96C9-11D0-A5E4-00609740F258),
	dual,
	helpstring("IFireCtrl Interface"),
	pointer_default(unique)
]
	
interface IFireCtrl : IDispatch
{
	[id(14), helpstring("method Up")] HRESULT Up();
	[id(15), helpstring("method Down")] HRESULT Down();
	[id(1), helpstring("method CreateFire")] HRESULT CreateFire();
	[propget, id(2), helpstring("property Temperature")] HRESULT Temperature([out, retval] short *pVal);
};

[
	uuid(23D68035-96C9-11D0-A5E4-00609740F258),
	version(1.0),
	helpstring("Fire 1.0 Type Library")
]
library FIRELib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	[
		uuid(23D68044-96C9-11D0-A5E4-00609740F258),
		helpstring("FireCtrl Class")
	]
	coclass FireCtrl
	{
		[default] interface IFireCtrl;
	};
};
